# Generated by Django 4.0.2 on 2022-02-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='RealEstate',
        ),
    ]
